### ISSUE TITLE
App doesnt exit on --help

### ISSUE THREAD

**Issue by trondhindenes** [natemcmaster/CommandLineUtils#217]
**Describe the bug**
If using the built-in `app.HelpOption();`, running the app with --help doesn't exit the app after printing help. This is cumbersome. The app should exit instead of locking

**Expected behavior**
The app should exit instead of locking

**Screenshots**
![screenshot from 2019-03-07 16-07-22](https://user-images.githubusercontent.com/1747120/53966306-39a73200-40f3-11e9-83f0-28e9ea07a54d.png)

**Additional context**
Running apps with complex parameters it's usual to just run --help first to get a sense of available options, and then start constructing the parameters one wishes to use. Since the app locks (and clears when exiting) this requires two side-by-side windows open, which shouldn't be necessary.

**Comment by trondhindenes** [comment]
From my limited understanding, it looks like `app.HelpOption()` implicitly adds a prompt, and imho this is wrong (or should at least be configurable)

**Comment by natemcmaster** [comment]
This behavior is by design. The paged output is intended to make it easier to search and scroll through help output.

To opt-out, update to 2.3.3 (released today) and use [this api](https://natemcmaster.github.io/CommandLineUtils/v2.3/api/McMaster.Extensions.CommandLineUtils.CommandLineApplication.html#McMaster_Extensions_CommandLineUtils_CommandLineApplication_UsePagerForHelpText) to suppress using paged console output:
```
app.UsePagerForHelpText = false;
```

Closing as this was addressed with https://github.com/natemcmaster/CommandLineUtils/pull/216.

**Comment by scott-vincent** [comment]
If I set app.UsePagerForHelpText = false; I no longer get the pager for top-level help but if I do <command> <subcommand> --help I still get the pager.

**Comment by natemcmaster** [comment]
@scott-vincent I'm not sure what is wrong. I'm currently not working on this project much due to recent birth of my first child. If you make any progress on this, please submit a pull request. If you can't figure out what is wrong on the code, please open a new issue with steps to reproduce the problem. Pull requests to fix a problem are always preferable to comments on closed issues about new problems.
